alias: ePaper Spielwiese 3.5
description: ePaper Spielwiese 3.5
mode: single
triggers:
  - hours: /3
    trigger: time_pattern
conditions:
  - condition: time
    after: "06:00:00"
    before: "20:00:00"
    weekday:
      - sat
      - fri
      - thu
      - wed
      - tue
      - mon
      - sun
actions:
  - target:
      entity_id:
        - open_epaper_link.780105562182A901
    data:
      background: white
      rotate: 0
      payload:
        - type: plot
          x_start: 10
          y_start: 40
          x_end: 150
          y_end: 90
          duration: 36000
          low: -10
          high: 20
          ylegend:
            position: right
            color: red
          yaxis:
            tick_width: 3
            grid: 5
          data:
            - entity: sensor.zgb_draussen_sensor_temperature
              width: 3
              color: red
        - type: icon
          value: home-thermometer-outline
          x: 10
          "y": 10
          size: 25
          color: black
        - type: text
          value: >-
            TEMP: {{ states('sensor.zgb_draussen_sensor_temperature') | round(1)
            }} °C
          font: ppb.ttf
          x: 50
          "y": 10
          size: 18
          color: black
        - type: text
          value: "Vorhersage: {{ states('sensor.baunatal_druck') }} hPa"
          font: ppb.ttf
          x: 20
          "y": 100
          size: 18
          color: black
    action: open_epaper_link.drawcustom
